### ISSUE TITLE
Feature request: Meteor.js integration

### ISSUE THREAD

**Issue by ryandeussing** [prismicio/javascript-nodejs-starter#14]
Please let me know where I should make this request, if not here. Thanks, I'm stoked to play with Prismic!

**Comment by erwan** [comment]
Hi,

Thank you for your interest in Prismic!

The Javascript kit should work with Meteor.js as with any other framework (https://github.com/prismicio/javascript-kit). This starter kit showcases Prismic on Express.js because it is probably the most popular framework on Node.js, and unfortunately we don't have enough ressources to create and maintain sample apps for more frameworks.

If you try to use Prismic in a Meteor.js application and encounter problems, don't hesitate to contact tech support (question mark in the bottom right of the dashboard) or open a ticket on the javascript-kit repository.
